### ISSUE TITLE
"timestamp-bkp-begin": "" - must not be empty

### ISSUE THREAD

**Issue by robert-bachmann** [Azure/azfilebackup#34]
Please check value "timestamp-bkp-begin": "". It is always empty but required value for our message processing. Every backup should have a start time, so why it is empty? Could you please correct that?

Thanks
Robert

**Comment by tomconte** [comment]
It seems this issue was fixed in #29 : previously the timestamp-bkp-begin was indeed an empty string.

The fix is included in the release I created yesterday: [v1.0-beta5](https://github.com/Azure/azfilebackup/releases/tag/v1.0-beta5). Could you please try it on a test system to make sure it fixes the issue?
